# Generated by Django 3.0.6 on 2020-05-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hamburger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.BigIntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('imagen', models.TextField()),
                ('ingredientes', models.ManyToManyField(to='hamburgers.Ingredient')),
            ],
        ),
    ]
